---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9
dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  system: bindep.txt
  galaxy: requirements.yml
  python: requirements.txt
# If proxy setup is needed, below portion can be removed
additional_build_steps:
  append_final:
     - ARG http_proxy=
     - ARG https_proxy=
  append_builder:
     - ARG http_proxy=
     - ARG https_proxy=
  append_galaxy:
     - ARG http_proxy=
     - ARG https_proxy=
  append_base:
     - ARG http_proxy=
     - ARG https_proxy=
